### ISSUE TITLE
Call to undefined method Bootstrap\View\Widget\DateTimeWidget::_normalizeData

### ISSUE THREAD

**Issue by starlocke** [CakePHP-Bootstrap/cakephp4-bootstrap-helpers#1]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] question

* CakePHP Version: 4.0.10
* Plugin Version/Branch: "holt59/cakephp4-bootstrap-helpers": "v3.0.0.x-dev"

### What you did & What happened

While migrating from CakePHP 3.8 to CakePHP 4.0, I switched to using this "cakephp4" helper. When I load an "edit" page that contains a "date" field, the system runs into an error complaining about `Call to undefined method Bootstrap\View\Widget\DateTimeWidget::_normalizeData()` because CakePHP has removed `_normalizeData()` from the DateTimeWidget on Dec 17, 2018 with commit [e88d4c91c9002590d85062b478968c38ec6713eb](https://github.com/cakephp/cakephp/commit/e88d4c91c9002590d85062b478968c38ec6713eb)

### What you expected to happen

DateTimeWidget within cakephp4-bootstrap-helpers is no longer needed, as far as I can tell. Just a straight rendering of a native `<input type="date">` should be fine from now on.

**Comment by Holt59** [comment]
I've pushed multiple fixes to the v3.0.0 branch. I've run and fix the unit tests but I've not tested it with a proper application so let me know if it fixes it for you.

**Comment by starlocke** [comment]
Looks good to me. Considered fixed.

**Comment by starlocke** [comment]
Whereas the "fix" simply dropped this line:

https://github.com/Holt59/cakephp4-bootstrap-helpers/blob/841cd75bf5dba9142a140744449a551fda2ad0dd/src/View/Helper/FormHelper.php#L157

What's likely really needed is the restoration of the original default widget:

https://github.com/cakephp/cakephp/blob/6c9ff4d0adb8776b93a65500021e017340d2bba4/src/View/Helper/FormHelper.php#L173

... but maybe tweaked for the namespaces, something like this:

```
        'datetime' => ['Cake\View\Widget\DateTimeWidget', 'select'],
        'year' => ['Cake\View\Widget\YearWidget', 'select'],
```

There's also a "YearWidget" now, for some reason.

**Comment by Holt59** [comment]
Should be fixed. There is a `step` attribute that popups on the `<input>` sometimes now but I don't have time to investigate and I guess it comes from Cake directly.

**Comment by starlocke** [comment]
I believe that new the fix worked out.
